#!/bin/bash

echo -e "\nSTART\t: `pwd`/$0\t `date`"

if [ "$SUDO_USER" != "" ]; then
  echo "ERROR	: This script must be run by non sudo user"
  echo "TRY	:   sudo scripts/$0"
  exit -1
fi

function cmd() {
    echo -e "CMD\t: $1"
    $1
    RC=$?; 
    if [ $RC != 0 ]; then 
        echo "ERROR\t: $1 => $RC"; 
        if [ "$2" == "" ]; then 
            exit -1; 
        else
            $2
        fi
    fi
}

####################### nodejs

echo -e "INFO\t: machine:`uname -m`"

NODEVER=v5.5.0
if [ "`uname -m`" == "x86_64" ]; then
    NODEINST=node-$NODEVER-linux-x64
elif [ "`uname -m`" == "armv7l" ]; then
    NODEINST=node-$NODEVER-linux-armv7l
elif [ "`uname -m`" == "i686" ]; then
    NODEINST=node-$NODEVER-linux-x86
else
    echo -e "ERROR\t: Could not install nodejs automatically"
    echo -e "TRY\t: Manual installation from https://nodejs.org/dist/v5.5.0/"
    exit -1
fi

if [ "$NODEINST" != "" ]; then
    echo "INFO	: Installing $NODEINST locally..."
    if [ ! -e $NODEINST.tar.gz ]; then
        echo -e "INFO\t: Downloading $NODEINST"
        wget https://nodejs.org/dist/$NODEVER/$NODEINST.tar.gz
        RC=$?; if [ $RC != 0 ]; then echo "ERROR\t: installation failed (wget:$RC)"; exit -1; fi
    fi
    if [ ! -e $NODEINST ]; then
        tar -xzf $NODEINST.tar.gz
    fi
    RC=$?; if [ $RC != 0 ]; then echo "ERROR\t: installation failed (tar:$RC)"; exit -1; fi
    ln -s -f $NODEINST/bin/node node
    ln -s -f $NODEINST/bin/npm npm
    echo -e "INFO\t: installed as `pwd`/node and `pwd`/npm"
else
    echo -e "ERROR\t: Could not install nodejs automatically"
    echo -e "TRY\t: Manual installation from https://nodejs.org/dist/v5.5.0/"
    exit -1
fi
#cmd "npm install serialport@2.0.2", "echo -e 'INFO\t: using firestep cli'"
echo -e "INFO\t: ./node `./node --version`"
echo -e "INFO\t: ./npm `./npm --version`"
cmd "npm install"

